apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoair
  labels:
    app: contosoair
    kubernetes.azure.com/generator: draft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair
  template:
    metadata:
      labels:
        app: contosoair
    spec:
      containers:
        - name: contosoair
          image: bestacr.azurecr.io/contosoair:018a4fa8bfe232ee97a57c8aad30be4d336bf690
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
