apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: contoso-air:68601d0155998bfcd5d571b95c5a449343544fabx
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
