apiVersion: apps/v1
kind: Deployment
metadata:
  name: testflow
  labels:
    app: testflow
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1736798693789
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testflow
  template:
    metadata:
      labels:
        app: testflow
    spec:
      containers:
        - name: testflow
          image: reiClusterregistry.azurecr.io/image-workflow-1736798693789:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
